import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dummyData from '../public/dummyData'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="flex w-400">
          <div className="grid max-w-sm grid-cols-1 mx-auto text-center divide-y p-8">
            {dummyData.map((data) => (
              <div key={data.title} className="py-8 pr-8 flex">
                <img className="h-20 w-20 rounded-md" src={data.image} alt="" />
                <div className="ml-8 mt-4 flex-col content-center">
                  <p className="text-xl">{data.title}</p>
                  <p className="text-sm">{data.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
